#spring:
#  shardingsphere:
#    datasource:
#      type: com.alibaba.druid.pool.DruidDataSource
#      names: wmaster,wslave0,wslave1
#      wslave0:
#        password: root
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/wslave0
#        username: root
#      wslave1:
#        password: root
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/wslave1
#        username: root
#      wmaster:
#        password: root
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/wmaster
#        username: root
#    masterslave:
#      #round_robin 表示轮询
#      load-balance-algorithm-type: round_robin
#      slave-data-source-names: wslave0,wslave1
#      name: ms
#      master-data-source-name: wmaster
#    props:
#      sql:
#        show: true
#
#
#
#mybatis:
# mapper-locations: classpath:/mybatis-mapper/*Mapper.xml
#mybatis-plus:
# mapper-locations: classpath:mapper/*.xml
# type-aliases-package: com.yl.shardingsphere.inline_demo.entity
